# COMMENT COLLECTION SETTINGS
MAX_COMMENTS = 100

# SCROLL DELAY RANGE (SECONDS)
MIN_SCROLL_DELAY = 2
MAX_SCROLL_DELAY = 4

# OR, STOP IF NO NEW COMMENTS LOAD AFTER THIS MANY SCROLL ATTEMPTS
MAX_NO_NEW_SCROLLS = 3